scalar Date

input CreateClienteInput {
  nome: String
  email: String
  password: String
  identificacao: String
}

enum TipoCliente {
  CLIENTE_PJ
  CLIENTE_FISICO
  ADMIN
}

type Cliente {
  nome: String
  email: String
  password: String
  identificacao: String

  tipoCliente: TipoCliente

  id: ID
  idb: String
  createdAt: Date
  updated: Date
  ultimoLogin: Date
}

# ##############################################
# PONTOS DE ENTRADAS :: CONSULTAS & MUTACOES
# ##############################################

type Query {
  helloCliente: String
#   getClientes: [Cliente]!
}

type Mutation {
#   createCliente(nome: String, email: String, password: String, identificacao: String): Cliente
}
