{
  desempacotar_dados: `MELHOR DESEMPACOTAR SOMENTE NO SERVICO QUE É UM MANIPULADOR E PRECISA DAS VARIAVEIS PASSADAS AO SEU DISPOR. `,

  contrato_request: `DEFINIR CAMPOS OBRIGATORIOS E POUCOS OU NENHUM OPCIONAL..OPCIONAL TENATR CRIAR UM INPUT TS SÓ DE OPCIONAIS OU SE FOR POO EXTENDER UAM CLASSE DE OPCIONAIS E USA-LA JUNTO`,
}